
Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end


# The SHELL is a file within this file, whihc will run the commands in it when the vagrant file is loaded
  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    echo "whoami..."
    whoami

    echo "pwd..."
    pwd

    #echo "upgrading..."
    #sudo yum upgrade -y

    echo "installing httpd..."
    # https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-centos-8
    sudo yum install httpd -y
# there are 2 options for installitation, yum OR dnf. They are both going to work fine
    sudo systemctl enable httpd
    sudo systemctl start httpd
    sudo systemctl status httpd

    echo "Hello World..."
    sudo cp /vagrant/index.html /var/www/html/index.html
    
  SHELL

end
