Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "forwarded_port", guest: 8443, host: 8081

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

	echo "whoami..."
	whoami

	echo "pwd..."
	pwd

	echo "upgrading..."
	sudo dnf upgrade -y

	echo "INSTALLING GIT..."
	sudo dnf install git -y
	echo "FINISH INSTALLING GIT"

	echo "INSTALLING JAVA..."
	sudo dnf install java-11-openjdk-devel -y
	export JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
	echo "FINISH INSTALLING JAVA"

	echo "INSTALLING GRADLE..."
	echo "making /opt/gradle directory..."
	sudo mkdir /opt/gradle

	echo "installing gradle 6.8.2..."
	sudo dnf install unzip -y
	cd /opt/gradle
	sudo curl -sLo \
	gradle-6.8.2-bin.zip \
	https://services.gradle.org/distributions/gradle-6.8.2-bin.zip
	sudo unzip gradle-6.8.2-bin.zip
	sudo rm gradle-6.8.2-bin.zip
	export GRADLE_HOME=/opt/gradle/gradle-6.8.2
	export PATH=$GRADLE_HOME/bin:$PATH

	# Profile.d

	echo "creating /etc/profile.d/gradle.sh..."
	sudo touch /etc/profile.d/gradle.sh
	sudo chown vagrant.vagrant /etc/profile.d/gradle.sh
sudo cat << `EOF` >> /etc/profile.d/gradle.sh
export GRADLE_HOME=/opt/gradle/gradle-6.8.2
export PATH=$GRADLE_HOME/bin:$PATH 
`EOF`
	sudo chown root.root /etc/profile.d/gradle.sh
	sudo chmod 644 /etc/profile.d/gradle.sh
	echo "FINISH INSTALLING GRADLE"
	
	echo "INSTALLING MARIADB..."
	sudo dnf install mariadb-server -y
	sudo systemctl start mariadb
	sudo systemctl status mariadb
	sudo systemctl enable mariadb
	echo "FINISH INSTALLING MARIADB"

	echo "INSTALLING GITLAB SERVER KEY..."
	echo "making git.cardiff.ac.uk a known and trusted host"
	cd /home/vagrant # going to the defualt directory (~)
	touch .ssh/known_hosts
	ssh-keyscan git.cardiff.ac.uk >> .ssh/known_hosts
	chmod 644 .ssh/known_hosts
	ECHO "FINISH INSTALLING GITLAB SERVER KEY"

	echo "INSTALLING JENKINS..."
	sudo dnf install wget -y
	sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
	sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
	sudo dnf install jenkins java-11-openjdk-devel -y
	sudo systemctl start jenkins
	sudo systemctl enable jenkins
	sudo systemctl status jenkins
	sleep 60
	echo "---------------------------------------------------------------------"
	echo "initial admin password:"
	sudo cat /var/lib/jenkins/secrets/initialAdminPassword
	echo "---------------------------------------------------------------------"
	echo "FINISH INSTALLING JENKINS"

	echo "FINISH PREPARING VM"

  SHELL

end