
Vagrant.configure("2") do |config|

  config.vm.box = "centos/8"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    #echo "whoami..."
    #whoami

    #echo "pwd..."
    #pwd

    #echo "upgrading..."
    #sudo yum upgrade -y

sudo yum install wget -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum install jenkins java-1.8.0-openjdk-devel -y
sudo systemctl start jenkins
sudo systemctl status jenkins
sudo cat /var/lib/jenkins/secrets/initialAdminPassword

  SHELL

end
